name: Deploy Next.js to GitHub Pages

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Define the environment to run the job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js to build the Next.js app
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the latest supported Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build and export the app
      - name: Build and export Next.js
        run: |
          npm run build
          npm run export

      # Step 5: Deploy the static files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out